export const SET_REMINDER_VALUE = "SET_REMINDER_VALUE";
export const OPEN_ADD_REMINDER = "OPEN_ADD_REMINDER";
export const ADD_REMINDER = "ADD_REMINDER";
export const OPEN_EDIT_REMINDER = "OPEN_EDIT_REMINDER";
export const EDIT_REMINDER = "EDIT_REMINDER";
export const REMOVE_ALL_REMINDERS = "REMOVE_REMINDERS";
export const REMOVE_REMINDER = "REMOVE_REMINDER";
export const CANCEL_EDITING = "CANCEL_EDITING";
